/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import javax.swing.JOptionPane;
import Operaciones.*;

/**
 *
 * @author soberanis
 */
public class ClcInterfaz extends javax.swing.JFrame {


    private int posicion;
    private double ans, resul;
    private OperacionesBasicas basicas = new OperacionesBasicas();
    private OperacionesConvertidoras convertidoras = new OperacionesConvertidoras();
    private OperacionesDiscretas discretas = new OperacionesDiscretas();
    private String cadena;
    private boolean valor=true, validez=true;
    
    public ClcInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        Paneles = new javax.swing.JTabbedPane();
        CalculosDiscretos = new javax.swing.JPanel();
        btnFactorial = new javax.swing.JButton();
        btnPermutacion = new javax.swing.JButton();
        btnCombinacion = new javax.swing.JButton();
        btnSeparador = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        ConvertidorNumerico = new javax.swing.JPanel();
        btnHexadecimal = new javax.swing.JButton();
        btnOctal = new javax.swing.JButton();
        btnBinario = new javax.swing.JButton();
        OperacionesBasicas = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnAns = new javax.swing.JButton();
        btnResiduo = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        Datos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setSize(new java.awt.Dimension(350, 300));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnFactorial.setText("Factorial");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnPermutacion.setText("Permutacion");
        btnPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermutacionActionPerformed(evt);
            }
        });

        btnCombinacion.setText("Combinacion");
        btnCombinacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombinacionActionPerformed(evt);
            }
        });

        btnSeparador.setText("/");
        btnSeparador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeparadorActionPerformed(evt);
            }
        });

        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalculosDiscretosLayout = new javax.swing.GroupLayout(CalculosDiscretos);
        CalculosDiscretos.setLayout(CalculosDiscretosLayout);
        CalculosDiscretosLayout.setHorizontalGroup(
            CalculosDiscretosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculosDiscretosLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(CalculosDiscretosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculosDiscretosLayout.createSequentialGroup()
                        .addGroup(CalculosDiscretosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCombinacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPermutacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculosDiscretosLayout.createSequentialGroup()
                        .addComponent(btnSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        CalculosDiscretosLayout.setVerticalGroup(
            CalculosDiscretosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculosDiscretosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnFactorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPermutacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCombinacion)
                .addGap(18, 18, 18)
                .addGroup(CalculosDiscretosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInstrucciones)
                    .addComponent(btnSeparador))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Paneles.addTab("Cálculos Discretos", CalculosDiscretos);

        btnHexadecimal.setText("a Hexadecimal");
        btnHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexadecimalActionPerformed(evt);
            }
        });

        btnOctal.setText("a Octal");
        btnOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOctalActionPerformed(evt);
            }
        });

        btnBinario.setText("a Binario");
        btnBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConvertidorNumericoLayout = new javax.swing.GroupLayout(ConvertidorNumerico);
        ConvertidorNumerico.setLayout(ConvertidorNumericoLayout);
        ConvertidorNumericoLayout.setHorizontalGroup(
            ConvertidorNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConvertidorNumericoLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(ConvertidorNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        ConvertidorNumericoLayout.setVerticalGroup(
            ConvertidorNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConvertidorNumericoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnHexadecimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOctal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBinario)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Paneles.addTab("Convertidor Numérico", ConvertidorNumerico);

        btnSuma.setText("+");
        btnSuma.setMaximumSize(new java.awt.Dimension(50, 50));
        btnSuma.setMinimumSize(new java.awt.Dimension(50, 50));
        btnSuma.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setText("-");
        btnResta.setMaximumSize(new java.awt.Dimension(50, 50));
        btnResta.setMinimumSize(new java.awt.Dimension(50, 50));
        btnResta.setPreferredSize(new java.awt.Dimension(50, 50));
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.setMaximumSize(new java.awt.Dimension(50, 50));
        btnIgual.setMinimumSize(new java.awt.Dimension(50, 50));
        btnIgual.setPreferredSize(new java.awt.Dimension(50, 50));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMultiplicacion.setText("*");
        btnMultiplicacion.setMaximumSize(new java.awt.Dimension(50, 50));
        btnMultiplicacion.setMinimumSize(new java.awt.Dimension(50, 50));
        btnMultiplicacion.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.setMaximumSize(new java.awt.Dimension(50, 50));
        btnDivision.setMinimumSize(new java.awt.Dimension(50, 50));
        btnDivision.setPreferredSize(new java.awt.Dimension(50, 50));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnPotencia.setText("^");
        btnPotencia.setMaximumSize(new java.awt.Dimension(50, 50));
        btnPotencia.setMinimumSize(new java.awt.Dimension(50, 50));
        btnPotencia.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });

        btnRaiz.setText("n raiz de");
        btnRaiz.setMaximumSize(new java.awt.Dimension(105, 50));
        btnRaiz.setMinimumSize(new java.awt.Dimension(105, 50));
        btnRaiz.setPreferredSize(new java.awt.Dimension(105, 50));
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnAns.setText("Ans");
        btnAns.setMaximumSize(new java.awt.Dimension(50, 50));
        btnAns.setMinimumSize(new java.awt.Dimension(50, 50));
        btnAns.setPreferredSize(new java.awt.Dimension(50, 50));
        btnAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsActionPerformed(evt);
            }
        });

        btnResiduo.setText("%");
        btnResiduo.setMaximumSize(new java.awt.Dimension(50, 50));
        btnResiduo.setMinimumSize(new java.awt.Dimension(50, 50));
        btnResiduo.setPreferredSize(new java.awt.Dimension(50, 50));
        btnResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResiduoActionPerformed(evt);
            }
        });

        btnPunto.setText(".");
        btnPunto.setMaximumSize(new java.awt.Dimension(50, 50));
        btnPunto.setMinimumSize(new java.awt.Dimension(50, 50));
        btnPunto.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperacionesBasicasLayout = new javax.swing.GroupLayout(OperacionesBasicas);
        OperacionesBasicas.setLayout(OperacionesBasicasLayout);
        OperacionesBasicasLayout.setHorizontalGroup(
            OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesBasicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesBasicasLayout.createSequentialGroup()
                        .addGroup(OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(OperacionesBasicasLayout.createSequentialGroup()
                                .addComponent(btnResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OperacionesBasicasLayout.createSequentialGroup()
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAns, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(OperacionesBasicasLayout.createSequentialGroup()
                        .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OperacionesBasicasLayout.setVerticalGroup(
            OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesBasicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAns, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OperacionesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Paneles.addTab("Operaciones Básicas", OperacionesBasicas);

        Datos.setText("?");
        Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(Paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Paneles)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsActionPerformed
        if(!valor){
            Texto.setText("");
            reiniciarValores();
            Texto.setText(Texto.getText()+"Ans");        
        }else{
            Texto.setText(Texto.getText()+"Ans");
        }
    }//GEN-LAST:event_btnAnsActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        btnAns.setEnabled(false); btnSuma.setEnabled(false); btnResta.setEnabled(false); btnResiduo.setEnabled(false);
        btnMultiplicacion.setEnabled(false); btnDivision.setEnabled(false); btnPotencia.setEnabled(false);
        btnRaiz.setEnabled(false);
        if(Texto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No se ingreso el número de la raíz que se desea obtener.");
            habilitarBotones();
        }else{
            Texto.setText(Texto.getText()+"RaizDe");
            posicion = Texto.getText().indexOf("R");
        }
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        btnAns.setEnabled(false); btnSuma.setEnabled(false); btnResta.setEnabled(false);btnDivision.setEnabled(false);
        btnMultiplicacion.setEnabled(false); btnPotencia.setEnabled(false);btnRaiz.setEnabled(false);btnResiduo.setEnabled(false);
        if(Texto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"No se ingreso la base de la potencia.");
            habilitarBotones();
        }else{
            Texto.setText(Texto.getText()+"^");
            posicion = Texto.getText().indexOf("^");
        }
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        btnSuma.setEnabled(false); btnResta.setEnabled(false);btnResiduo.setEnabled(false);
        btnMultiplicacion.setEnabled(false); btnPotencia.setEnabled(false);btnRaiz.setEnabled(false);
        if(!valor){
            Texto.setText("");
            reiniciarValores();
        }
        Texto.setText(Texto.getText()+"/");
        posicion = Texto.getText().indexOf("/");
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        btnSuma.setEnabled(false); btnResta.setEnabled(false);btnDivision.setEnabled(false);
        btnPotencia.setEnabled(false);btnRaiz.setEnabled(false);btnResiduo.setEnabled(false);
        if(!valor){
            Texto.setText("");
            reiniciarValores();
        }
        Texto.setText(Texto.getText()+"*");
        posicion = Texto.getText().indexOf("*");
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        operacion();
        Texto.setText(String.valueOf(resul));
        ans=resul;
        valor=false;
        habilitarBotones();
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        btnSuma.setEnabled(false);btnDivision.setEnabled(false);btnResiduo.setEnabled(false);
        btnMultiplicacion.setEnabled(false); btnPotencia.setEnabled(false);btnRaiz.setEnabled(false);
        if(!valor){
            Texto.setText("");
            reiniciarValores();
        }
        Texto.setText(Texto.getText()+"-");
        posicion = Texto.getText().indexOf("-");
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        btnResta.setEnabled(false);btnDivision.setEnabled(false);btnResiduo.setEnabled(false);
        btnMultiplicacion.setEnabled(false); btnPotencia.setEnabled(false);btnRaiz.setEnabled(false);
        if(!valor){
            reiniciarValores();
            Texto.setText("");
        }
        Texto.setText(Texto.getText()+"+");
        posicion = Texto.getText().indexOf("+");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResiduoActionPerformed
        btnSuma.setEnabled(false); btnResta.setEnabled(false);btnDivision.setEnabled(false);
        btnMultiplicacion.setEnabled(false); btnPotencia.setEnabled(false);btnRaiz.setEnabled(false);
        if(!valor){
            Texto.setText("");
            reiniciarValores();
        }
        Texto.setText(Texto.getText()+"%");
        posicion = Texto.getText().indexOf("%");
    }//GEN-LAST:event_btnResiduoActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        JOptionPane.showMessageDialog(null,"Para la cominación y\n" +
                                        "permutación se requiere\n" +
                                        "el formato siguiente:\n" +
                                        "'N/R' donde el número\n" +
                                        "n y r serán separados por\n" +
                                        "'/'.");
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermutacionActionPerformed
        if(!valor){
            Texto.setText("");
        }
        if(!Texto.getText().isEmpty()){
            try{
                Double[] vector = new Double[Texto.getText().split("\\/").length];
                for (int i = 0; i < vector.length; i++) {
                    vector[i] = Double.parseDouble(Texto.getText().split("\\/")[i]);
                }
                if(vector.length>2||vector[0]<vector[1]){
                    JOptionPane.showMessageDialog(null, "Ingresó mas de una vez el signo '/', o r es mayor que n.");
                }else{
                    resul = discretas.opcionPermutacion(vector[0].intValue(), vector[1].intValue());
                    ans = resul;
                    Texto.setText(String.valueOf(resul));
                    valor=false;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "La expresion ingresada no es válida.");
            }
        }else{JOptionPane.showMessageDialog(null, "Primero ingrese algo.");}
    }//GEN-LAST:event_btnPermutacionActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        if(!valor){
            Texto.setText("");
        }
        if(!Texto.getText().isEmpty()){
            try{
                resul = discretas.opcionFactorial(Integer.parseInt(Texto.getText()));
                Texto.setText(String.valueOf(resul));
                valor=false;
                ans = resul;
                valor=false;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"No se ingresó un valor válido.");
            }
        }else{JOptionPane.showMessageDialog(null, "Primero ingrese algo.");}
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnSeparadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeparadorActionPerformed
        if(!valor){
            Texto.setText("");
            reiniciarValores();
        }
        Texto.setText(Texto.getText()+"/");
    }//GEN-LAST:event_btnSeparadorActionPerformed

    private void btnCombinacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombinacionActionPerformed
        if(!valor){
            Texto.setText("");
        }
        if(!Texto.getText().isEmpty()){
            try{
                Double[] vector = new Double[Texto.getText().split("\\/").length];
                for (int i = 0; i < vector.length; i++) {
                    vector[i] = Double.parseDouble(Texto.getText().split("\\/")[i]);
                }
                if(vector.length>2||vector[0]<vector[1]){
                    JOptionPane.showMessageDialog(null, "Ingresó mas de una vez el signo '/', o r es mayor que n.");
                }else{
                    resul = discretas.opcionCombinacion(vector[0].intValue(),vector[1].intValue());
                    ans = resul;
                    Texto.setText(String.valueOf(resul));
                    valor=false;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "La expresion ingresada no es válida.");
            }
        }else{JOptionPane.showMessageDialog(null, "Primero ingrese algo.");}
    }//GEN-LAST:event_btnCombinacionActionPerformed

    private void btnHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexadecimalActionPerformed
        if(!valor){
            Texto.setText("");
        }
        if(!Texto.getText().isEmpty()){
            try{
                resul = convertidoras.opcionDecimalAHexadecimal(Integer.parseInt(Texto.getText()));
                Texto.setText(String.valueOf(resul));
                valor=false;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"No se ingresó un valo válido.");
            }
        }
    }//GEN-LAST:event_btnHexadecimalActionPerformed

    private void btnOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOctalActionPerformed
        if(!valor){
            Texto.setText("");
        }
        if(!Texto.getText().isEmpty()){
            try{
                resul = convertidoras.opcionDecimalAOctal(Integer.parseInt(Texto.getText()));
                Texto.setText(String.valueOf(resul));
                valor=false;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"No se ingresó un valo válido.");
            }
        }
    }//GEN-LAST:event_btnOctalActionPerformed

    private void btnBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinarioActionPerformed
        if(!valor){
            Texto.setText("");
        }
        if(!Texto.getText().isEmpty()){
            try{
                resul = convertidoras.opcionDecimalABinario(Integer.parseInt(Texto.getText()));
                Texto.setText(String.valueOf(resul));
                valor=false;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"No se ingresó un valo válido.");
            }
        }
    }//GEN-LAST:event_btnBinarioActionPerformed

    private void DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosActionPerformed
        JOptionPane.showMessageDialog(null,"Desarrolladores: \nJuan Pablo Orizabal Gil\nJosé Carlos Soberanis Ramírez.\nVersion: 3.3","Datos de la aplicacion",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_DatosActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if(!valor){
            Texto.setText("");
            reiniciarValores();
        }
        Texto.setText(Texto.getText()+".");
    }//GEN-LAST:event_btnPuntoActionPerformed

    public void reiniciarValores(){
        posicion=0;
        valor=true;
        validez=true;
        resul=0;
    }
    
    public void operacion(){
        if(Texto.getText().equals("Ans")){
            resul = ans;
            Texto.setText(String.valueOf(resul));
        }
        if(Texto.getText().contains("+")){
        Double[] vector = new Double[Texto.getText().split("\\+").length];
            try{
                for (int i = 0; i < Texto.getText().split("\\+").length; i++) {
                    if(Texto.getText().split("\\+")[i].equals("Ans")){
                        vector[i]= ans;
                    }else{
                        vector[i] = Double.parseDouble(Texto.getText().split("\\+")[i]);
                    }
                }
                ans = basicas.operacionSuma(vector[0], vector[1]);
                if(vector.length>2){
                    for (int i = 2; i < vector.length; i++) {
                        ans = basicas.operacionSuma(ans,vector[i]);
                    }
                }
                resul=ans;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ingresaron algunos valores válidos,o hay '+' seguidos.");
            }
        }
        if(Texto.getText().contains("-")){
        Double[] vector = new Double[Texto.getText().split(("\\-")).length];
            try{
                for (int i = 0; i < Texto.getText().split("\\-").length; i++) {
                    if(Texto.getText().split("\\-")[i].equals("Ans")){
                        vector[i]= ans;
                    }else{
                        vector[i] = Double.parseDouble(Texto.getText().split("\\-")[i]);
                    }
                }
                ans = basicas.operacionResta(vector[0], vector[1]);
                if(vector.length>2){
                    for (int i = 2; i < vector.length; i++) {
                        ans = basicas.operacionResta(ans,vector[i]);
                    }
                }
                resul=ans;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ingresaron algunos valores válidos, o hay '-' seguidos.");
            }
        }
        if(Texto.getText().contains("*")){
        Double[] vector = new Double[Texto.getText().split(("\\*")).length];
            try{
                for (int i = 0; i < Texto.getText().split("\\*").length; i++) {
                    if(Texto.getText().split("\\*")[i].equals("Ans")){
                        vector[i]= ans;
                    }else{
                        vector[i] = Double.parseDouble(Texto.getText().split("\\*")[i]);
                    }
                }
                ans = basicas.operacionMultiplicacion(vector[0], vector[1]);
                if(vector.length>2){
                    for (int i = 2; i < vector.length; i++) {
                        ans = basicas.operacionMultiplicacion(ans,vector[i]);
                    }
                }
                resul=ans;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ingresaron algunos valores válidos, o hay '*' seguidos.");
            }
        }
        if(Texto.getText().contains("/")){
        Double[] vector = new Double[Texto.getText().split(("\\/")).length];
            try{
                for (int i = 0; i < Texto.getText().split("\\/").length; i++) {
                    if(Texto.getText().split("\\/")[i].equals("Ans")){
                        vector[i]= ans;
                    }else{
                        vector[i] = Double.parseDouble(Texto.getText().split("\\/")[i]);
                    }
                }
                ans = basicas.operacionDivision(vector[0], vector[1]);
                if(vector.length>2){
                    for (int i = 2; i < vector.length; i++) {
                      ans = basicas.operacionDivision(ans,vector[i]);
                    }
                }
                resul=ans;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ingresaron algunos valores válidos, o hay '/' seguidos.");
            }
        }
        if(Texto.getText().contains("%")){
        Double[] vector = new Double[Texto.getText().split(("\\%")).length];
            try{
                for (int i = 0; i < Texto.getText().split("\\%").length; i++) {
                    if(Texto.getText().split("\\%")[i].equals("Ans")){
                        vector[i]= ans;
                    }else{
                        vector[i] = Double.parseDouble(Texto.getText().split("\\%")[i]);
                    }
                }
                ans = basicas.operacionResiduo(vector[0], vector[1]);
                if(vector.length>2){
                    for (int i = 2; i < vector.length; i++) {
                      ans = basicas.operacionResiduo(ans,vector[i]);
                    }
                }
                resul=ans;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ingresaron algunos valores válidos, o hay '%' seguidos.");
            }
        }
        if(Texto.getText().contains("^")){
            Double base, exponente;
            try{
                if(Texto.getText().substring(0, posicion).equals("Ans")){
                    base = ans;
                }else{
                    base = Double.parseDouble(Texto.getText().substring(0,posicion));
                }
                exponente = Double.parseDouble(Texto.getText().substring(posicion+1,Texto.getText().length()));
                resul = basicas.operacionPotencia(exponente, base);
                ans = resul;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ingresaron algunos valores validos.");
            }
        }
        if(Texto.getText().contains("RaizDe")){
            Double exponente, base;
            try{
                if(Texto.getText().substring(0,posicion).equals("Ans")){
                    exponente = ans;
                }else{
                    exponente = Double.parseDouble(Texto.getText().substring(0,posicion));
                }
                base = Double.parseDouble(Texto.getText().substring(posicion+6,Texto.getText().length()));
                resul = basicas.operacionRaiz(exponente, base);
                ans = resul;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ingresaron algunos valores validos.");
            }
        }
    }
    
    public void habilitarBotones(){
        btnSuma.setEnabled(true); btnResta.setEnabled(true); btnMultiplicacion.setEnabled(true);
        btnDivision.setEnabled(true); btnPotencia.setEnabled(true); btnRaiz.setEnabled(true);
        btnAns.setEnabled(true);btnResiduo.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClcInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClcInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClcInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClcInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClcInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalculosDiscretos;
    private javax.swing.JPanel ConvertidorNumerico;
    private javax.swing.JButton Datos;
    private javax.swing.JPanel OperacionesBasicas;
    private javax.swing.JTabbedPane Paneles;
    private javax.swing.JTextField Texto;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAns;
    private javax.swing.JButton btnBinario;
    private javax.swing.JButton btnCombinacion;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnHexadecimal;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnOctal;
    private javax.swing.JButton btnPermutacion;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResiduo;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeparador;
    private javax.swing.JButton btnSuma;
    // End of variables declaration//GEN-END:variables
}
